module.exports = message = {
    paymentDetail: "you card has been added successfully",
    paymentList: "find payment list here",
    updatepayment: "payment detail updated successfully",
    deletepayment: "payment has been deleted successfully",
    notExist: "email not exist",
    dataNotFound: "no data found",
    addproduct: "product has been added successfully",
    productList: " find product list here",
    updateproduct: "product detail updated successfully",
    deleteproduct: "product has been deleted successfully",
    cardExists: "card is allready exists please use diffrent",
    registerUser: " you have been register successfully",
    userList: "find user list here",
    updateUser: "user detail updated successfully",
    deleteUser: "user has been deleted successfully",
    cardExists: "card is allready exists please use diffrent",
    invalidCrad: "invalid cradeintial",
    emailExist: "email allready exists please use another email",
    idNotExist: "invalid id",
    internalServerError: "Internal server error",
    logIn: " you have been log in successfully",
    tokenExpire: "token has been expired",
    vendorNotExit: " vendor not exist",
    vendorValidation: " you are not a valid vendor",
    adminValidation: " you are not a valid admin"
}